resolver: nightly-2017-08-17
packages:
- .
- hie-apply-refact
- hie-base
- hie-build-plugin
- hie-eg-plugin-async
- hie-example-plugin2
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
- hie-hoogle
- hie-plugin-api
- hie-brittany
- location:
    git: https://github.com/alanz/haskell-lsp.git
    commit: 50076561c9c9e4d86536efd9458ac3f1d14a68a4
  extra-dep: true
- location:
    git: https://github.com/robrix/brittany.git
    commit: 7a6be9c6dfb7655e6d2c74fe6d09504dd79c6312
  extra-dep: true
- location:
    git: https://github.com/robrix/ghc-dump-tree.git
    commit: 2e3dc742e6a701f3b9615a3d5a7d0dbc02cd60d4
  extra-dep: true
- location:
    git: https://github.com/robrix/HaRe.git
    commit: 0426ea379e57f2f82119126895eb8a773cd8337f
  extra-dep: true
- location:
    git: https://github.com/robrix/cabal-helper.git
    commit: ba29c035264ae6a4cd2ad4c582adbe1f765fbe3d
  extra-dep: true
- location:
    git: https://github.com/robrix/ghc-mod.git
    commit: 043c70385857b28bf61cd7086b2c59ec2e65f740
  extra-dep: true
  subdirs:
    - .
    - ghc-mod-core

extra-deps:
- apply-refact-0.4.1.0
- butcher-1.1.0.1
- czipwith-1.0.0.0
- data-tree-print-0.1.0.0
- deque-0.2
- ghc-8.2.1
- monad-memo-0.4.1
- hoogle-5.0.13
- brittany-0.8.0.2
- syz-0.2.0.0
flags:
  haskell-ide-engine:
    pedantic: true
  hie-apply-refact:
    pedantic: true
  hie-base:
    pedantic: true
  hie-eg-plugin-async:
    pedantic: true
  hie-example-plugin2:
    pedantic: true
  hie-ghc-mod:
    pedantic: true
  hie-ghc-tree:
    pedantic: true
  hie-hare:
    pedantic: true
  hie-hoogle:
    pedantic: true
  hie-plugin-api:
    pedantic: true
  hie-brittany:
    pedantic: true
